apiVersion: coriolis.cloudbase.it/v1alpha1
kind: CoriolisAppliance
metadata:
  name: example
spec:
  profile: core
  version: "2603.4"
  ingress:
    host: coriolis.app.cloudbase.wiki
    ingressClassName: nginx
    tls:
      mode: certManager
      clusterIssuer: letsencrypt
  logging:
    retentionHours: 24
    storage:
      loki:
        storageClassName: local-path
        size: 10Gi
    resources:
      loki:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 1Gi
      gateway:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 64Mi
      alloy:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      adaptor:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
