apiVersion: coriolis.cloudbase.it/v1alpha1
kind: CoriolisAppliance
metadata:
  name: example
spec:
  profile: core
  version: "2603.4"
  ingress:
    host: coriolis.app.cloudbase.wiki
    ingressClassName: nginx
    tls:
      mode: certManager
      clusterIssuer: letsencrypt
