# CIXpress owns future synchronized release updates.
image:
  repository: cr.virtomat.io/virtomat/coriolis/operator
  tag: "0.5.14"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: "coriolis-operator"
serviceAccount:
  create: true
  name: ""
logLevel: INFO
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
nodeSelector: {}
tolerations: []
affinity: {}
podSecurityContext:
  runAsNonRoot: true
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
liveness:
  port: 8080
  path: /healthz
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
